name: CI

on:
  push:
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest